In [1]:
import numpy as np

In [ ]:
# CREATION des tableau
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6]])
print("a:", a)
print("b:\n", b)
print("Type:", type(a))
print("ndim:", b.ndim, "shape:", b.shape, "size:", b.size) # Affichage de la dimension d'une table et de la  forme
print("dtype:", a.dtype)

=== INTRODUCTION & CREATION ===
a: [1 2 3]
b:
 [[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>
ndim: 2 shape: (2, 3) size: 6
dtype: int64


In [ ]:
zeros = np.zeros((3, 3))
ones = np.ones((2, 4), dtype=int) # matrice constitue des un seulement
eye = np.eye(4)  # matrice identité
ar = np.arange(0, 10, 2)
lin = np.linspace(0, 1, 5)
rand = np.random.rand(3, 2) # generation des valeurs aleatoires
print("zeros:\n", zeros)
print("ones:\n", ones)
print("eye:\n", eye)
print("arange:", ar)
print("linspace:", lin)
print("rand:\n", rand)

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1 1 1 1]
 [1 1 1 1]]
eye:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]
rand:
 [[0.10189604 0.65359006]
 [0.77307483 0.15269028]
 [0.47140085 0.54512667]]


In [ ]:
# INDEXATION, SLICING, MASQUES
# generations des valeurs allant de 0 a 19 et les passer dansun tableau numpy
arr = np.arange(20).reshape(4,5)
print("arr:\n", arr)
print("arr[1,2]:", arr[1,2])
print("arr[1]:", arr[1]) #Accessibilite a une valeur a partir de son index



arr:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
arr[1,2]: 7
arr[1]: [5 6 7 8 9]


In [ ]:
#Accessibilite a des valeur du tableau avec le slicing
print("arr[:,2]:", arr[:,2])
print("arr[1:3, 2:5]:\n", arr[1:3, 2:5])


arr[:,2]: [ 2  7 12 17]
arr[1:3, 2:5]:
 [[ 7  8  9]
 [12 13 14]]


In [ ]:
mask = arr % 2 == 0
# returne vrai si celui ci est pair ou faux dans le cas contraire
print("mask (pairs):\n", mask)
print("valeurs paires:", arr[mask]) #aficichage des reu=sultat des valeurs paires

mask (pairs):
 [[ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]]
valeurs paires: [ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
# Operation Arithmetique et trigonometrique
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
print(f"{x}  +  {y} =   ", x+y) # calcul de la somme
print(f"{x}  *  {y} = ", x*y)
print(f"{y}  /  {x} =  ", y/x)
print(f"{x}  **2   =  ", x**2)
print(f"sqrt({x}): ", np.sqrt(x)) # caclu de la racine carre
print(f"exp({x}):  ", np.exp(x))   # calcul de l'exponentielle de x
print(f"sin({x}):  ", np.sin(x)) # calcul du sin

[1 2 3 4]  +  [5 6 7 8] =    [ 6  8 10 12]
[1 2 3 4]  *  [5 6 7 8] =  [ 5 12 21 32]
[5 6 7 8]  /  [1 2 3 4] =   [5.         3.         2.33333333 2.        ]
[1 2 3 4]  **2   =   [ 1  4  9 16]
sqrt([1 2 3 4]):  [1.         1.41421356 1.73205081 2.        ]
exp([1 2 3 4]):   [ 2.71828183  7.3890561  20.08553692 54.59815003]
sin([1 2 3 4]):   [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [ ]:
# Algebre lineaire
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print("A:\n", A)
print("B:\n", B)

A:
 [[1 2]
 [3 4]]
B:
 [[5 6]
 [7 8]]


In [ ]:
print("Produit matriciel(A,B):\n", A.dot(B))  # Calcule matriciel
print("matmul(A,B):\n", A @ B)   # calcul du produit de 2 matrices

dot(A,B):
 [[19 22]
 [43 50]]
matmul(A,B):
 [[19 22]
 [43 50]]


In [ ]:
print("detrminant(A):", np.linalg.det(A)) # calcul du determinant de la matrice
print("La matrice inverse de (A):\n", np.linalg.inv(A))  # calcul de la matrice inverse

detrminant(A): -2.0000000000000004
La matrice inverse de (A):
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
# Generation des valeurs aleatoires & statistiques
data = np.random.randint(0,100,size=(5,4))
print("data:\n", data)
print("mean:", data.mean()) # calcul de la moyenne
print("mean axis=0 :", data.mean(axis=0))  # calcul de la moyenne par colonne
print("sum axis = 1 (lignes):", data.sum(axis=1))  # calcul de la moyenne par ligne
print("median:", np.median(data)) # calcul du medianne
print("std:", np.std(data))
print("argmax:", data.argmax(), "argmin:", data.argmin()) # Affichage de la valeur maximale et minimal


data:
 [[23 52 40 31]
 [63 72 80  3]
 [14 79 68 51]
 [55 37 30 10]
 [84 88 58 21]]
mean: 47.95
mean axis=0 : [47.8 65.6 55.2 23.2]
sum axis = 1 (lignes): [146 218 212 132 251]
median: 51.5
std: 25.527387253692847
argmax: 17 argmin: 7


In [ ]:
# Tri les element d'un tableau ou d'une liste
D = np.array([5,2,9,1,7])
print("trie:", np.sort(arr))
index = np.argsort(arr)
print("trie a a   index:", index)
print("arr[idx]:", D[index])

trie: [1 2 5 7 9]
trie a a   index: [3 1 0 4 2]
arr[idx]: [1 2 5 7 9]
